spring:
  application:
    name: chatbot-Java-IA
  datasource:
    url: jdbc:h2:mem:cji2024
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

openAi:
  baseUrl: https://api.openai.com
  api-key: ${OPENAI_API_KEY}

geminiAi:
  baseUrl: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_API_KEY}